 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"BlueProximity", "start_proximity.sh", "/usr/share/pixmaps/blueproximity.xpm" },
     {"Catarina", "catarina", "/usr/share/icons/hicolor/16x16/apps/catarina.png" },
     {"ClipIt", "clipit"},
     {"Elementary Test", "elementary_test", "/usr/share/icons/elementary.png" },
     {"Frescobaldi", "frescobaldi "},
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Genius Math Tool", "gnome-genius ", "/usr/share/icons/hicolor/32x32/apps/gnome-genius.png" },
     {"Gnome-Pie", "gnome-pie"},
     {"KeePassX", "keepassx ", "/usr/share/pixmaps/keepassx.xpm" },
     {"Leafpad", "leafpad ", "/usr/share/icons/hicolor/16x16/apps/leafpad.png" },
     {"LilyTerm", "lilyterm", "/usr/share/pixmaps/lilyterm.png" },
     {"QtPass", "qtpass"},
     {"Redshift", "redshift-gtk"},
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"SpaceFM File Search", "spacefm --find-files ", "/usr/share/icons/hicolor/48x48/apps/spacefm-find.png" },
     {"Variety", "variety ", "///usr/share/variety/media/variety.svg" },
     {"compton", "compton"},
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Genius Math Tool", "gnome-genius ", "/usr/share/icons/hicolor/32x32/apps/gnome-genius.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Lutris", "lutris ", "/usr/share/pixmaps/lutris.png" },
     {"RuneScape", "/opt/runescape/runescape ", "///opt/runescape/share/img/runescape.png" },
     {"RuneScape OldSchool", "/opt/runescape/runescape --prmfile=oldschool.prm", "///opt/runescape/share/img/runescape.png" },
     {"Runescape Client Updater", "xterm -e /opt/runescape/rsu/rsu-query rsu.download.client", "///opt/runescape/share/img/update-runescape.png" },
     {"Speed Dreams", "speed-dreams-2", "/usr/share/pixmaps/speed-dreams.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"SuperTuxKart", "supertuxkart", "/usr/share/pixmaps/supertuxkart_128.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Feh", "feh ", "///usr/share/feh/images/feh.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gromit-MPX", "gromit-mpx", "/usr/share/pixmaps/gromit-mpx.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Mirage", "mirage ", "/usr/share/pixmaps/mirage.png" },
     {"XSane - Scanning", "xsane", "/usr/share/pixmaps/xsane.xpm" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Deluge", "deluge-gtk ", "/usr/share/icons/hicolor/16x16/apps/deluge.png" },
     {"Dianara", "dianara", "/usr/share/icons/hicolor/32x32/apps/dianara.png" },
     {"Dropbox", "dropbox", "/usr/share/pixmaps/dropbox.png" },
     {"Firefox", "firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Earth", "/opt/google/earth/free/google-earth ", "/usr/share/icons/hicolor/16x16/apps/google-earth.png" },
     {"Lutris", "lutris ", "/usr/share/pixmaps/lutris.png" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Mumble", "mumble"},
     {"NetSurf Web Browser", "netsurf "},
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Toxic", "xterm -e toxic", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Webby", "webby "},
     {"X11VNC Server", "x11vnc -gui tray=setpass -rfbport PROMPT -bg -o %HOME/.x11vnc.log.%VNCDISPLAY", "/usr/share/icons/gnome/16x16/devices/computer.png" },
     {"X2Go Desktop Sharing", "/usr/bin/x2godesktopsharing", "/usr/share/icons/hicolor/16x16/apps/x2godesktopsharing.png" },
     {"qTox", "qtox ", "/usr/share/icons/hicolor/16x16/apps/qtox.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Gummi", "gummi ", "/usr/share/pixmaps/gummi.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"TeXstudio", "texstudio "},
     {"Texmaker", "texmaker ", "/usr/share/pixmaps/texmaker.png" },
     {"Zathura", "zathura "},
     {"ePDFViewer", "epdfview ", "/usr/share/icons/hicolor/24x24/apps/epdfview.png" },
     {"qpdfview", "qpdfview --unique "},
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"D-Feet", "d-feet", "/usr/share/icons/hicolor/16x16/apps/d-feet.png" },
     {"Elementary Test", "elementary_test", "/usr/share/icons/elementary.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Ardour 4", "ardour4", "///usr/share/ardour4/icons/ardour_icon_256px.png" },
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Cadence", "cadence", "/usr/share/icons/hicolor/16x16/apps/cadence.png" },
     {"Calf Plugin Pack for JACK", "calfjackhost", "/usr/share/icons/hicolor/16x16/apps/calf.png" },
     {"Carla", "carla ", "/usr/share/icons/hicolor/16x16/apps/carla.png" },
     {"Carla Control", "carla-control", "/usr/share/icons/hicolor/16x16/apps/carla-control.png" },
     {"Catia", "catia", "/usr/share/icons/hicolor/16x16/apps/catia.png" },
     {"Claudia", "claudia", "/usr/share/icons/hicolor/16x16/apps/claudia.png" },
     {"Claudia Launcher", "claudia-launcher", "/usr/share/icons/hicolor/16x16/apps/claudia-launcher.png" },
     {"FFADO Mixer", "ffado-mixer", "/usr/share/pixmaps/ffado.png" },
     {"Frescobaldi", "frescobaldi "},
     {"Hydrogen Drum Machine", "hydrogen "},
     {"Kodi Media Center", "kodi", "/usr/share/icons/hicolor/16x16/apps/kodi.png" },
     {"LMMS", "env QT_X11_NO_NATIVE_MENUBAR=1 lmms", "/usr/share/pixmaps/lmms.png" },
     {"Lightworks", "/usr/bin/lightworks", "///usr/share/lightworks/Icons/App.png" },
     {"MuseScore", "mscore ", "/usr/share/pixmaps/mscore.png" },
     {"MusicBrainz Picard", "picard ", "/usr/share/icons/hicolor/16x16/apps/picard.png" },
     {"OBS", "obs", "/usr/share/icons/hicolor/256x256/apps/obs.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QjackCtl", "/usr/bin/qjackctl", "/usr/share/icons/hicolor/32x32/apps/qjackctl.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qtractor", "/usr/bin/qtractor", "/usr/share/icons/hicolor/32x32/apps/qtractor.png" },
     {"Rosegarden", "rosegarden ", "/usr/share/icons/hicolor/32x32/apps/rosegarden.png" },
     {"Toxic", "xterm -e toxic", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"XJadeo", "xjadeo", "/usr/share/pixmaps/xjadeo.png" },
     {"ZynAddSubFX - Alsa", "zynaddsubfx -I alsa -O alsa", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"ZynAddSubFX - Jack", "zynaddsubfx -I jack -O jack", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"Zynaddsubfx", "zynaddsubfx", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"guitarix", "guitarix", "/usr/share/pixmaps/gx_head.png" },
     {"mpv Media Player", "mpv --profile=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"qTox", "qtox ", "/usr/share/icons/hicolor/16x16/apps/qtox.png" },
     {"tuxguitar", "tuxguitar  -Dorg.eclipse.swt.internal.gtk.cairoGraphics=false", "///usr/share/tuxguitar/share/skins/Lavender/icon-96x96.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Add/Remove Software", "pamac-manager", "/usr/share/icons/hicolor/16x16/apps/system-software-install.png" },
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Exterminator", "exterminator", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Grsync", "/usr/bin/grsync -i ", "/usr/share/pixmaps/grsync.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LXTerminal", "lxterminal", "/usr/share/icons/hicolor/128x128/apps/lxterminal.png" },
     {"LiveUSB Install", "gksu python2 /usr/share/live-usb-install/live-usb-install.py", "/usr/share/pixmaps/live-usb-install.png" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Manage Printing", "gtklp", "/usr/share/icons/gnome/16x16/devices/printer.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Manage Printing Queue", "gtklpq", "/usr/share/icons/gnome/16x16/devices/printer.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"SUSE Studio Imagewriter", "imagewriter ", "/usr/share/icons/hicolor/32x32/apps/imagewriter.png" },
     {"Sakura", "sakura", "/usr/share/pixmaps/terminal-tango.svg" },
     {"Software Update", "pamac-updater", "/usr/share/icons/gnome/16x16/apps/system-software-update.png" },
     {"SpaceFM", "spacefm ", "/usr/share/icons/hicolor/48x48/apps/spacefm.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"Terminology", "terminology", "/usr/share/icons/terminology.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"mrxvt", "mrxvt", "/usr/share/pixmaps/mrxvt.png" },
     {"tkPacman", "/usr/bin/tkpacman", "///usr/share/tkpacman/icons/tkpacman-icon.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

